from typing import Optional


class Node:
    element: int
    def __init__(self, element: int): ...


class Tree:
    def __init__(self): ...
    def __len__(self) -> int: ...

    def get(self, element: int) -> Optional[int]: ...
    def insert(self, element: int) -> None: ...